name: 📥 GitHub Request - Core Contributor Onboarding
description: Add new user(s) to the openedx GitHub organization with appropriate access.
title: "[GH Request] Onboard <ADD USERNAMES HERE>"
labels: ["github-request"]
body:
  - type: markdown
    attributes:
      value: |
        ## Core Contributor Onboarding
        This request type is specifically for users who have gone through a Core Contributor vote to become a new Core Contributor or expand existing rights. If you are only looking for Triage permissions, please use the Triage Onboarding issue type.

        ## GitHub Change Request
        Please leave [GH Request] in the title of your ticket!
  - type: input
    id: firm
    attributes:
      label: Firm Name
      description: Which firm are you from (ex Axim, 2U, ...)
      placeholder:
    validations:
      required: true
  - type: textarea
    id: users
    attributes:
      label: User List (case sensitive!) - Please also include in ticket title
      description: Which user(s) are you requesting access for? Note GitHub usernames are case-sensitive, so please enter in the correct capitalization.
      placeholder: |
        * Full Name Here, @username_here
        * ...
    validations:
      required: true
  - type: input
    id: ccthread
    attributes:
      label: Core Contributor nomination thread
      description: Please link the forums nomination thread here.
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Email address
      description: We need to know your email address. You can provide it here, but if you'd rather not post it on a public form, then we'll Slack DM you to ask for it.
  - type: textarea
    id: requests
    attributes:
      label: Special Requests
      description: If these users need to be added to any specific Github teams or given any elevated privileges, note them here.
  - type: markdown
    attributes:
      value: "## Once you create this request, the Axim engineering team will triage it and handle it as appropriate. If your request is especially urgent, please note that above!"
