name: 📥 GitHub Request - Onboarding
description: Add new user(s) to the openedx GitHub organization with appropriate access.
title: "[GH Request] Onboard <ADD USERNAMES HERE>"
labels: ["github-request"]
body:
  - type: markdown
    attributes:
      value: |
        ## GitHub Change Request
        Please leave [GH Request] in the title of your ticket!
  - type: input
    id: firm
    attributes:
      label: Firm Name
      description: Which firm are you from (ex Axim, 2U, ...)
      placeholder:
    validations:
      required: true
  - type: textarea
    id: users
    attributes:
      label: User List (case sensitive!) - Please also include in ticket title
      description: Which user(s) are you requesting access for? Note GitHub usernames are case-sensitive, so please enter in the correct capitalization.
      placeholder: |
        * Full Name Here, @username_here
        * ...
    validations:
      required: true
  - type: input
    id: squad
    attributes:
      label: User Squad
      description: If the users specified above are members of a named squad or team at your firm, optionally specify it here.  This will help simplify access management in the future.
  - type: input
    id: ccthread
    attributes:
      label: Core Contributor nomination thread
      description: If the user specified is onboarding as a Core Contributor, please link the forums nomination thread here.
  - type: input
    id: start-date
    attributes:
      label: Start Date
      description: Date of first need for GitHub access.
      placeholder: 29 February 2020
    validations:
      required: true
  - type: dropdown
    id: urgent
    attributes:
      label: Urgency
      description: How urgent is this request?
      options:
        - Low (2 weeks)
        - Medium (< 2 weeks)
        - High (< 3 days)
    validations:
      required: true
  - type: textarea
    id: requests
    attributes:
      label: Special Requests
      description: If these users need to be added to any specific Github teams or given any elevated privileges, note them here.
  - type: markdown
    attributes:
      value: "## Once you create this request, the Axim engineering team will triage it and handle it as appropriate. If your request is especially urgent, please note that above!"
