name: 🔐 GitHub Request - Repos/Access/Config
description: Make specific changes to the openedx organization (new repo, grant/revoke user access, change config, etc).
title: "[GH Request] <ADD A REQUEST TITLE HERE>"
labels: ["github-request"]
body:
  - type: markdown
    attributes:
      value: |
        ## GitHub Request - Access/Config
        Please leave [GH Request] in the title of your ticket!
        
        Use this ticket to request specific, small changes (like app config or repo secrets) where you don't have
        the appropriate GitHub permissions to do so.
  - type: input
    id: firm
    attributes:
      label: Firm Name
      description: Which firm are you from (ex tCRIL, 2U, ...)
      placeholder: tCRIL
    validations:
      required: true
  - type: input
    id: urgent
    attributes:
      label: Urgency
      description: How urgent is this request and why? What's your timeline?
      placeholder: Low urgency - done in next 3 weeks is fine
    validations:
      required: true
  - type: textarea
    id: request
    attributes:
      label: Requested Change
      description: Describe what you want changed. If you're referencing users, include both usernames and full names. If you're requesting a new repo, include who the maintainer will be and have them comment on this request to confirm their willingness.
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Reasoning
      description: Describe why you want this change to be made.
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Once you create this request, the tCRIL engineering team will triage it and handle it as appropriate. If your request is especially urgent, please note that above!"
