name: 📤 GitHub Request - Offboarding
description: Remove user(s) from the openedx GitHub organization.
title: "[GH Request] Offboard <ADD USERNAMES HERE>"
labels: ["github-request"]
body:
  - type: markdown
    attributes:
      value: |
        ## GitHub Change Request
        Please leave [GH Request] in the title of your ticket!
  - type: input
    id: firm
    attributes:
      label: Firm Name
      description: Which firm are you from (ex Axim, 2U, ...)
      placeholder:
    validations:
      required: true
  - type: textarea
    id: users
    attributes:
      label: User List  (case sensitive!) - Please also include in ticket title
      description: Which user(s) are being offboarded? Note GitHub usernames are case-sensitive, so please enter in the correct capitalization.
      placeholder: |
        * Full Name Here, @username_here
        * ...
    validations:
      required: true
  - type: input
    id: end-date
    attributes:
      label: End Date
      description: Date of last need for GitHub access.
      placeholder: 29 February 2020
    validations:
      required: true
  - type: dropdown
    id: urgent
    attributes:
      label: Urgency
      description: How urgent is this request?
      options:
        - Low (2 weeks)
        - Medium (< 2 weeks)
        - High (< 3 days)
    validations:
      required: true
  - type: textarea
    id: retained-perms
    attributes:
      label: Retained Permissions & Special Requests
      description: By default, these users will be removed from the openedx organization and lose all team memberships and repository permissions. If any of the users should instead retain some permissions as "outside collaborators", please note that here.
  - type: markdown
    attributes:
      value: "## Once you create this request, the Axim engineering team will triage it and handle it as appropriate. If your request is especially urgent, please note that above!"
